services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: karrio-dev
    command: karrio runserver 0.0.0.0:5002
    ports:
      - 5002:5002
    volumes:
      - .:/code
