name: karrio-build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changes.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            version:
              - 'apps/api/karrio/server/VERSION'

  server-build:
    needs: changes
    if: ${{ needs.changes.outputs.version == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: get_tag
        run: |
          cat ./apps/api/karrio/server/VERSION
          echo "tag=$(cat ./apps/api/karrio/server/VERSION)" >> "$GITHUB_ENV"

      - name: Build karrio server image
        run: |
          echo 'Building karrio server:${{ env.tag }}...'
          ./bin/build-server-image-from-source ${{ env.tag }}

      - name: Push karrio server image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          echo 'Pushing karrio server:${{ env.tag }}...'
          docker push karrio/server:${{ env.tag }}
          docker tag karrio/server:${{ env.tag }} karrio/server:latest-rc
          docker push karrio/server:latest-rc

  dashboard-build:
    needs: changes
    if: ${{ needs.changes.outputs.version == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: get_tag
        run: |
          cat ./apps/api/karrio/server/VERSION
          echo "tag=$(cat ./apps/api/karrio/server/VERSION)" >> "$GITHUB_ENV"

      - name: Build karrio dashboard image
        run: |
          echo 'Building karrio dashboard:${{ env.tag }}...'
          export NEXT_PUBLIC_DASHBOARD_VERSION=${{ env.tag }}
          export NEXT_PUBLIC_KARRIO_VERSION="http://locahost:5002"
          ./bin/build-dashboard-image ${{ env.tag }}

      - name: Push karrio dashboard image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          echo 'Pushing karrio dashboard:${{ env.tag }}...'
          docker push karrio/dashboard:${{ env.tag }}
          docker tag karrio/dashboard:${{ env.tag }} karrio/dashboard:latest-rc
          docker push karrio/dashboard:latest-rc

  insiders-build:
    needs: changes
    if: ${{ needs.changes.outputs.version == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - id: get_tag
        run: |
          cat ./apps/api/karrio/server/VERSION
          echo "tag=$(cat ./apps/api/karrio/server/VERSION)" >> "$GITHUB_ENV"

      - name: Build insider server image
        run: |
          echo 'Build and push karrio-insiders server:${{ env.tag }}...'
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
          ./bin/build-insiders-image ${{ env.tag }} &&
          docker push ghcr.io/karrioapi/server:${{ env.tag }} || exit 1

      - name: Build insider dashboard image
        run: |
          echo 'Build and push karrio-insiders dashboard:${{ env.tag }}...'
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
          KARRIO_IMAGE=ghcr.io/karrioapi/dashboard ./bin/build-dashboard-image ${{ env.tag }} &&
          docker push ghcr.io/karrioapi/dashboard:${{ env.tag }} || exit 1
